name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run Semgrep SAST
      uses: returntocorp/semgrep-action@v1
      with:
        config: 'p/default'

    - name: Run OWASP ZAP (DAST)
      uses: zaproxy/action-baseline@v0.6.0
      with:
        target: 'https://juice-shop.herokuapp.com'
