name: DevSecOps CI/CD Enhanced

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security-scan:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run npm audit (Dependency Vulnerability Scan)
        run: npm audit --audit-level=high

      - name: Run Semgrep (SAST - Static Analysis)
        uses: returntocorp/semgrep-action@v1
        with:
          config: 'p/default'

      - name: Run OWASP ZAP Baseline Scan (DAST - Dynamic Analysis)
        uses: zaproxy/action-baseline@v0.6.0
        with:
          target: 'https://juice-shop.herokuapp.com'
          fail_action: false
          docker_name: ghcr.io/zaproxy/zaproxy:stable
          issue_title: ZAP Scan Baseline Report
          allow_issue_writing: true

      - name: Upload ZAP HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint (Code Quality + Potential Security Issues)
        run: npx eslint . --max-warnings=0

      - name: Scan for secrets with Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --verbose

      - name: Summary
        run: echo "✅ SAST, DAST, Dependency Scanning, Linting, and Secrets Detection complete."
